### ISSUE TITLE
currentRetryAttempt is not unique by request

### ISSUE THREAD

**Issue by denizaydemir** [JustinBeckwith/retry-axios#61]
Same currentRetryAttempt value is shared by all the request made by an axios instance. This leads to unreliable retry attempts when working with mass parallel requests.

**Comment by ScottChapman** [comment]
I think this is leading to the other issue I've discovered; the retry count doesn't reset after success? I've been testing with a mocked server which is generating ratelimits for different intervals. I can see the requests happen, then it succeeds. But the next request that happens it appears that the retry counter did not get reset...

**Comment by JustinBeckwith** [comment]
Greetings folks!  I am having a little trouble pinning this one down.  Does someone have a small piece of code I can use to reproduce the problem?

**Comment by Atomic71** [comment]
Hello sir, first of all, thanks for this great tool. I've created a repository which you can just clone and run 'yarn test' in order to start dealing with the problem. Hope it helps!

https://github.com/tomic-dvica-golf/retry-axios-demo/tree/master

**Comment by yoshigev** [comment]
Hi @JustinBeckwith ,
I've also encountered this problem.
I think it can be described by the following test (can be incorporated into test/index.ts tests):
```
  it('should reset error counter upon success', async () => {
    const scopes = [
      nock(url)
        .get('/')
        .times(2)
        .reply(500),
      nock(url)
        .get('/')
        .reply(200, 'milk'),
      nock(url)
        .get('/')
        .reply(500),
      nock(url)
        .get('/')
        .reply(200, 'toast')
    ];
    interceptorId = rax.attach();
    const cfg: rax.RaxConfig = { url, raxConfig: { retry: 2 } };
    const res = await axios(cfg);
    assert.strictEqual(res.data, 'milk');
    const res2 = await axios(cfg);
    assert.strictEqual(res2.data, 'toast');
    scopes.forEach(s => s.done());
  });
```
This test fails, as `currentRetryAttempt` equals 2 after the first call to `axios()`, so the second call to `axios()` has no more retries left.

The expected behavior is having a separate `currentRetryAttempt` counter for each call to `axios()` (even if they are running concurrently, which could happen in a backend that serves multiple requests in parallel).

---

A workaround is adding `cfg.raxConfig.currentRetryAttempt = 0;` before the second call to `axios()`. However, the correct solution is not to hold the counter as part of the configuration, but as part of the request object.

**Comment by yoshigev** [comment]
A better workaround is to only shallow-copy the raxConfig object. It can be done by storing axiosConfig and raxConfig on separate objects, and for each call to axios() copy it like:

```
    const res = await axios({ ...axiosConfig, raxConfig: { ...raxConfig } });
```

In any case, I've submitted a PR that does something similar, but inside rax code.

**Comment by denizaydemir** [comment]
Nice approach @yoshigev thx. This gets rid of unnecessary manual request counting and resetting.

**Comment by yoshigev** [comment]
@JustinBeckwith, can you take a look on my PR?
