### ISSUE TITLE
I set retry 3 times，but only retry 1 times

### ISSUE THREAD

**Issue by CatcherRao** [JustinBeckwith/retry-axios#68]
```js
raxConfig: {
    retry: 3,
    noResponseRetries: 5,
    instance: http,
    retryDelay: 100,
    httpMethodsToRetry: ['GET', 'OPTIONS', 'POST'],
    shouldResetTimeout: false,
    onRetryAttempt: (err) => {
      const cfg = rax.getConfig(err);
      console.log(cfg.currentRetryAttempt);
    }
  }
```

**Comment by tehaksbrid** [comment]
Is the axios instance being shared? I ran into a similar issue and found that the retry counter is shared between multiple uses of a single instance.

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share a complete code example that does this?  We have tests specifically covering number of retries, so an isolated example of how to break it would be *super* helpful.

**Comment by tehaksbrid** [comment]
@JustinBeckwith was that WRT my comment?
I assumed #61 was well-known. Wanted to confirm before I spent time making a clear example.

Also, thank you for the awesome tool. I use it in every lambda project.

**Comment by tomic-dvica-golf** [comment]
Hello @JustinBeckwith, thanks for the library.

Here is a reproducible demo for you: https://github.com/tomic-dvica-golf/retry-axios-demo/tree/master

just run yarn test.
hope you find it useful!

**Comment by yoshigev** [comment]
Note that #61 was fixed, so this issue is probably also fixed.

**Comment by JustinBeckwith** [comment]
Sweet.  Could I trouble anyone to try it and take a look?

**Comment by morevolk-latei** [comment]
Hi @JustinBeckwith, I ran into the same issue where I have specified both **retry count** and **noResponseRetries** to 3.

I have debugged the _**"retry-axios"**_ code and turns out that during the first initial request raxConfig received the correct value of **httpMethodsToRetry & statusCodesToRetry** i.e **Array**  which I have passed from my code as config.

But when an error occurred for first time, The response interceptor is being called with correct raxConfig and in that **shouldRetryRequest**  is called which returns **true** to retry the 1st attempt of the request.

Now, in this 1st attempt of retry, The response interceptor receives the incorrect raxConfig i.e the value of **httpMethodsToRetry** & **statusCodesToRetry** is **Object** this time but not **Array** therefore when **normalizeArray** is called from response interceptor it **receives Object** and return **empty Array**  hence **shouldRetryRequest** function return false as the condition `config.httpMethodsToRetry.indexOf(err.config.method.toUpperCase()) < 0` evaluates to **true**.

Please find the attached screenshots for a better understanding.

This is the Initial raxConfig when the first-time error occurred which in my case is timeout.
![First time error - rax config](https://user-images.githubusercontent.com/21017832/78004921-737b5400-7358-11ea-88d6-310ec24bd2c5.png)

Now this is the raxConfig for 1st retry attempt and error occurred, Here you can clearly see the value of **httpMethodsToRetry** & **statusCodesToRetry** is **Object** this time but not **Array**.
therefore  **normalizeArray** return **empty Array**
![Second time error - rax config](https://user-images.githubusercontent.com/21017832/78005170-ce14b000-7358-11ea-8b7a-3fae17de4a6f.png)

now for this error when **shouldRetryRequest** function called see the config now.
![Should retry method rax config](https://user-images.githubusercontent.com/21017832/78005312-01efd580-7359-11ea-8035-df30d9054863.png)

therefore `config.httpMethodsToRetry.indexOf(err.config.method.toUpperCase()) < 0` evaluates to **true** and 2nd retry won't happen.

Please look into the issue, I'm stuck in some very important project or allow me to debug this furthermore, let see if I can find a cause from where **Array is turning into Object**
Thanks.

**Comment by seahindeniz** [comment]
@JustinBeckwith I have setup a small environment on Repl.it to test it. Here https://repl.it/@seahindeniz/RaxRetryingIssue

**Comment by khitrenovich** [comment]
According to the printouts from @morevolk-latei, the keys in the object form are now strings instead of integers.

If so, the fix can be pretty simple - just replace
```
      if (typeof key === 'number') {
        arr[key] = obj[key];
      }
```
with
```
      const idx = parseInt(key, 10);
      if (!isNaN(idx)) {
        arr[idx] = obj[key];
      }
```

**Comment by orgads** [comment]
Here is a full example for timeout error:

```javascript
import axios from 'axios';
import * as rax from 'retry-axios';

const axiosConf = {
  timeout: 1000,
  raxConfig: {
    retry: 3,
    noResponseRetries: 3,
    httpMethodsToRetry: ['POST'],
    onRetryAttempt: (err) => {
      const cfg = rax.getConfig(err);
      console.log(`Retry attempt #${cfg?.currentRetryAttempt} (after ${err.code} for URL ${err.config?.url})`);
    }
  }
};

try {
  const axiosClient = axios.create();
  rax.attach(axiosClient);
  const res = await axiosClient.post('http://httpbin.org/delay/2', {}, axiosConf);
  console.log(res.data);
} catch (err) {
  console.error(err.message);
}
```

Output:
```
Retry attempt #1 (after ECONNABORTED for URL http://httpbin.org/delay/2)
timeout of 1000ms exceeded
```

**Comment by orgads** [comment]
Here is a simple example with error code:
```javascript
import axios from 'axios';
import * as rax from 'retry-axios';

try {
  const axiosClient = axios.create();
  rax.attach(axiosClient);
  console.log('Sending request');
  const res = await axiosClient.get('http://httpbin.org/status/503', {
    raxConfig: {
      retry: 3,
      noResponseRetries: 3,
      onRetryAttempt: (err) => {
        const cfg = rax.getConfig(err);
        console.log(`Retry attempt #${cfg?.currentRetryAttempt} (after ${err.code} for URL ${err.config?.url})`);
      }
    }
  });
  console.log(res.data);
} catch (err) {
  console.log(err.message);
}
```

Output:
```
Sending request
Retry attempt #1 (after ERR_BAD_RESPONSE for URL http://httpbin.org/status/503)
Request failed with status code 503
```
